Retry pecl installs 3 times before failing

diff --git a/php/Dockerfile-dev b/php/Dockerfile-dev
--- a/php/Dockerfile-dev
+++ b/php/Dockerfile-dev
@@ -13,6 +13,6 @@ RUN apt-get update -q -y \
         gdb-minimal \
         && rm -rf /var/lib/apt/lists/*
 
-# Install xdebug
-RUN echo yes | pecl install -o ${XDEBUG_CHANNEL}
+# Install xdebug (retry 3 times for buggy pecl connection)
+RUN for i in $(seq 1 3); do echo yes | pecl install -o ${XDEBUG_CHANNEL} && s=0 && break || s=$? && sleep 1; done; (exit $s)
 COPY conf.d/xdebug.ini ${PHP_INI_DIR}/conf.d/xdebug.ini
